-- Club names by season. hokej.cz match pages give a club's name of that season only from about
-- 2003, and even then not everywhere (generic "Pardubice", "Č. Budějovice"); before that they show
-- the current name (Třinec as "HC Oceláři Třinec" in 1995). The names below follow the clubs'
-- name histories on Czech Wikipedia (a rename in year Y applies from season Y/Y+1), taking
-- hokej.cz's name where Wikipedia's list is incomplete (Kometa since 2009, Dukla Jihlava) or
-- differs only in capitals (HC VERVA Litvínov). The current season reads team.name.
create table if not exists team_season_name (
  team_id text not null references team(id),
  league_id text not null,
  season int not null,
  name text not null,
  source text not null,
  primary key (team_id, league_id, season)
);
grant select on team_season_name to anon, authenticated;

insert into team_season_name (team_id, league_id, season, name, source) values
  ('hcz-11', 'cz-elh', 1995, 'HC Železárny Třinec', 'wikipedia'),
  ('hcz-11', 'cz-elh', 1996, 'HC Železárny Třinec', 'wikipedia'),
  ('hcz-11', 'cz-elh', 1997, 'HC Železárny Třinec', 'wikipedia'),
  ('hcz-11', 'cz-elh', 1998, 'HC Železárny Třinec', 'wikipedia'),
  ('hcz-11', 'cz-elh', 1999, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2000, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2001, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2002, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2003, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2004, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2005, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2006, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2007, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2008, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2009, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2010, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2011, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2012, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2013, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2014, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2015, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2016, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2017, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2018, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2019, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2020, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2021, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2022, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2023, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2024, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-11', 'cz-elh', 2025, 'HC Oceláři Třinec', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 1993, 'HC Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 1994, 'HC Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 1995, 'HC Pojišťovna IB Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 1996, 'HC Pojišťovna IB Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 1997, 'HC IPB Pojišťovna Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 1998, 'HC IPB Pojišťovna Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 1999, 'HC IPB Pojišťovna Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 2000, 'HC IPB Pojišťovna Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 2001, 'HC IPB Pojišťovna Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 2002, 'HC ČSOB Pojišťovna Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 2003, 'HC Moeller Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2004, 'HC Moeller Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2005, 'HC Moeller Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2006, 'HC Moeller Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2007, 'HC Moeller Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2008, 'HC Moeller Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2009, 'HC Eaton Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2010, 'HC Eaton Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2011, 'HC ČSOB Pojišťovna Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 2012, 'HC ČSOB Pojišťovna Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 2013, 'HC ČSOB Pojišťovna Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 2014, 'HC ČSOB Pojišťovna Pardubice', 'wikipedia'),
  ('hcz-12', 'cz-elh', 2015, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2016, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2017, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2018, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2019, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2020, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2021, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2022, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2023, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2024, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-12', 'cz-elh', 2025, 'HC Dynamo Pardubice', 'hokej.cz'),
  ('hcz-120', 'cz-elh', 1996, 'HK Kralupy nad Vltavou', 'hokej.cz'),
  ('hcz-126', 'cz-elh', 2005, 'HC Slovan Ústečtí Lvi', 'hokej.cz'),
  ('hcz-126', 'cz-elh', 2007, 'HC Slovan Ústečtí Lvi', 'hokej.cz'),
  ('hcz-126', 'cz-elh', 2008, 'HC Slovan Ústečtí Lvi', 'hokej.cz'),
  ('hcz-126', 'cz-elh', 2010, 'HC Slovan Ústečtí Lvi', 'hokej.cz'),
  ('hcz-128', 'cz-elh', 1995, 'HC Přerov', 'wikipedia'),
  ('hcz-16', 'cz-elh', 1993, 'ASD Dukla Jihlava', 'wikipedia'),
  ('hcz-16', 'cz-elh', 1994, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 1995, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 1996, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 1997, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 1998, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 1999, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 2003, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 2004, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 2015, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 2016, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 2017, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 2021, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 2024, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-16', 'cz-elh', 2025, 'HC Dukla Jihlava', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 1993, 'HC Stadion Hradec Králové', 'wikipedia'),
  ('hcz-1711', 'cz-elh', 2013, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2014, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2015, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2016, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2017, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2018, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2019, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2020, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2021, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2022, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2023, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2024, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1711', 'cz-elh', 2025, 'Mountfield HK', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 1993, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 1994, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 1995, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 1996, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 1997, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 1998, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 1999, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2000, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2001, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2002, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2003, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2004, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2005, 'HC České Budějovice', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2006, 'HC Mountfield', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2007, 'HC Mountfield', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2008, 'HC Mountfield', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2009, 'HC Mountfield', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2010, 'HC Mountfield', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2011, 'HC Mountfield', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2012, 'HC Mountfield', 'hokej.cz'),
  ('hcz-1721', 'cz-elh', 2014, 'ČEZ Motor České Budějovice', 'wikipedia'),
  ('hcz-1721', 'cz-elh', 2016, 'ČEZ Motor České Budějovice', 'wikipedia'),
  ('hcz-1721', 'cz-elh', 2018, 'ČEZ Motor České Budějovice', 'wikipedia'),
  ('hcz-1721', 'cz-elh', 2020, 'Madeta Motor České Budějovice', 'wikipedia'),
  ('hcz-1721', 'cz-elh', 2021, 'HC Motor České Budějovice', 'wikipedia'),
  ('hcz-1721', 'cz-elh', 2022, 'HC Motor České Budějovice', 'wikipedia'),
  ('hcz-1721', 'cz-elh', 2023, 'Banes Motor České Budějovice', 'wikipedia'),
  ('hcz-1721', 'cz-elh', 2024, 'Banes Motor České Budějovice', 'wikipedia'),
  ('hcz-1721', 'cz-elh', 2025, 'Banes Motor České Budějovice', 'wikipedia'),
  ('hcz-18', 'cz-elh', 2001, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2002, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2003, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2004, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2005, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2006, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2007, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2008, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2009, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2010, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2011, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2012, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2013, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2014, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2015, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2016, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2017, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2018, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2019, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2020, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2021, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2022, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2023, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2024, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-18', 'cz-elh', 2025, 'Bílí Tygři Liberec', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 1995, 'HC Kometa Brno BVV', 'wikipedia'),
  ('hcz-22', 'cz-elh', 2009, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2010, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2011, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2012, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2013, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2014, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2015, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2016, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2017, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2018, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2019, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2020, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2021, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2022, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2023, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2024, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-22', 'cz-elh', 2025, 'HC Kometa Brno', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 1993, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 1994, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 1995, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 1996, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2012, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2013, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2014, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2015, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2016, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2017, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2018, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2019, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2020, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2021, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2022, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2023, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2024, 'HC Olomouc', 'hokej.cz'),
  ('hcz-24', 'cz-elh', 2025, 'HC Olomouc', 'hokej.cz'),
  ('hcz-38', 'cz-elh', 1993, 'Jindř. Hradec', 'hokej.cz'),
  ('hcz-4', 'cz-elh', 1995, 'HC Slezan Opava', 'hokej.cz'),
  ('hcz-4', 'cz-elh', 1996, 'HC Bohemex Trade Opava', 'wikipedia'),
  ('hcz-4', 'cz-elh', 1997, 'HC Bohemex Trade Opava', 'wikipedia'),
  ('hcz-4', 'cz-elh', 1998, 'HC Opava', 'wikipedia'),
  ('hcz-5', 'cz-elh', 1996, 'HC Becherovka Karlovy Vary', 'wikipedia'),
  ('hcz-5', 'cz-elh', 1997, 'HC Becherovka Karlovy Vary', 'wikipedia'),
  ('hcz-5', 'cz-elh', 1998, 'HC Becherovka Karlovy Vary', 'wikipedia'),
  ('hcz-5', 'cz-elh', 1999, 'HC Becherovka Karlovy Vary', 'wikipedia'),
  ('hcz-5', 'cz-elh', 2000, 'HC Becherovka Karlovy Vary', 'wikipedia'),
  ('hcz-5', 'cz-elh', 2001, 'HC Becherovka Karlovy Vary', 'wikipedia'),
  ('hcz-5', 'cz-elh', 2002, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2003, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2004, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2005, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2006, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2007, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2008, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2009, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2010, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2011, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2012, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2013, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2014, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2015, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2016, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2017, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2018, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2019, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2020, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2021, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2022, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2023, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2024, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-5', 'cz-elh', 2025, 'HC Energie Karlovy Vary', 'hokej.cz'),
  ('hcz-549', 'cz-elh', 1993, 'TJ Zbrojovka Vsetín', 'wikipedia'),
  ('hcz-549', 'cz-elh', 1994, 'HC Dadák Vsetín', 'wikipedia'),
  ('hcz-549', 'cz-elh', 1995, 'HC Dadák Vsetín', 'wikipedia'),
  ('hcz-549', 'cz-elh', 1996, 'HC Petra Vsetín', 'wikipedia'),
  ('hcz-549', 'cz-elh', 1997, 'HC Petra Vsetín', 'wikipedia'),
  ('hcz-549', 'cz-elh', 1998, 'HC Slovnaft Vsetín', 'wikipedia'),
  ('hcz-549', 'cz-elh', 1999, 'HC Slovnaft Vsetín', 'wikipedia'),
  ('hcz-549', 'cz-elh', 2000, 'HC Slovnaft Vsetín', 'wikipedia'),
  ('hcz-549', 'cz-elh', 2001, 'HC Vsetín', 'wikipedia'),
  ('hcz-549', 'cz-elh', 2002, 'HC Vsetín', 'wikipedia'),
  ('hcz-549', 'cz-elh', 2003, 'Vsetínská hokejová', 'hokej.cz'),
  ('hcz-549', 'cz-elh', 2004, 'Vsetínská hokejová', 'hokej.cz'),
  ('hcz-549', 'cz-elh', 2005, 'Vsetínská hokejová', 'hokej.cz'),
  ('hcz-549', 'cz-elh', 2006, 'Vsetínská hokejová', 'hokej.cz'),
  ('hcz-549', 'cz-elh', 2023, 'VHK ROBE Vsetín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 1993, 'AC ZPS Zlín', 'wikipedia'),
  ('hcz-562', 'cz-elh', 1994, 'AC ZPS Zlín', 'wikipedia'),
  ('hcz-562', 'cz-elh', 1995, 'AC ZPS Zlín', 'wikipedia'),
  ('hcz-562', 'cz-elh', 1996, 'AC ZPS Zlín', 'wikipedia'),
  ('hcz-562', 'cz-elh', 1997, 'HC ZPS-Barum Zlín', 'wikipedia'),
  ('hcz-562', 'cz-elh', 1998, 'HC ZPS-Barum Zlín', 'wikipedia'),
  ('hcz-562', 'cz-elh', 1999, 'HC Barum Continental', 'wikipedia'),
  ('hcz-562', 'cz-elh', 2000, 'HC Barum Continental', 'wikipedia'),
  ('hcz-562', 'cz-elh', 2001, 'HC Continental Zlín', 'wikipedia'),
  ('hcz-562', 'cz-elh', 2002, 'HC Hamé', 'wikipedia'),
  ('hcz-562', 'cz-elh', 2003, 'HC Hamé', 'wikipedia'),
  ('hcz-562', 'cz-elh', 2004, 'HC Hamé', 'wikipedia'),
  ('hcz-562', 'cz-elh', 2005, 'HC Hamé', 'wikipedia'),
  ('hcz-562', 'cz-elh', 2006, 'HC Hamé', 'wikipedia'),
  ('hcz-562', 'cz-elh', 2007, 'RI Okna Zlín', 'wikipedia'),
  ('hcz-562', 'cz-elh', 2008, 'RI Okna Zlín', 'wikipedia'),
  ('hcz-562', 'cz-elh', 2009, 'PSG Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2010, 'PSG Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2011, 'PSG Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2012, 'PSG Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2013, 'PSG Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2014, 'PSG Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2015, 'PSG Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2016, 'PSG Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2017, 'Aukro Berani Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2018, 'PSG Berani Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2019, 'PSG Berani Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2020, 'PSG Berani Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2021, 'PSG Berani Zlín', 'hokej.cz'),
  ('hcz-562', 'cz-elh', 2022, 'PSG Berani Zlín', 'hokej.cz'),
  ('hcz-566', 'cz-elh', 1997, 'HC Excalibur Znojemští Orli', 'wikipedia'),
  ('hcz-566', 'cz-elh', 1998, 'HC Excalibur Znojemští Orli', 'wikipedia'),
  ('hcz-566', 'cz-elh', 1999, 'HC Excalibur Znojemští Orli', 'wikipedia'),
  ('hcz-566', 'cz-elh', 2000, 'HC Excalibur Znojemští Orli', 'wikipedia'),
  ('hcz-566', 'cz-elh', 2001, 'HC JME Znojemští Orli', 'wikipedia'),
  ('hcz-566', 'cz-elh', 2002, 'HC JME Znojemští Orli', 'wikipedia'),
  ('hcz-566', 'cz-elh', 2003, 'HC JME Znojemští Orli', 'wikipedia'),
  ('hcz-566', 'cz-elh', 2004, 'HC JME Znojemští Orli', 'wikipedia'),
  ('hcz-566', 'cz-elh', 2005, 'HC JME Znojemští Orli', 'wikipedia'),
  ('hcz-566', 'cz-elh', 2006, 'HC Znojemští Orli', 'hokej.cz'),
  ('hcz-566', 'cz-elh', 2007, 'HC Znojemští Orli', 'hokej.cz'),
  ('hcz-566', 'cz-elh', 2008, 'HC Znojemští Orli', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 1993, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 1994, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 1995, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 1996, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 1997, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 1998, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 1999, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 2000, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 2001, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 2002, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 2003, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 2004, 'HC Vítkovice', 'wikipedia'),
  ('hcz-7', 'cz-elh', 2005, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2006, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2007, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2008, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2009, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2010, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2011, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2012, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2013, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2014, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2015, 'HC VÍTKOVICE STEEL', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2016, 'HC VÍTKOVICE RIDERA', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2017, 'HC VÍTKOVICE RIDERA', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2018, 'HC VÍTKOVICE RIDERA', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2019, 'HC VÍTKOVICE RIDERA', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2020, 'HC VÍTKOVICE RIDERA', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2021, 'HC VÍTKOVICE RIDERA', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2022, 'HC VÍTKOVICE RIDERA', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2023, 'HC VÍTKOVICE RIDERA', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2024, 'HC VÍTKOVICE RIDERA', 'hokej.cz'),
  ('hcz-7', 'cz-elh', 2025, 'HC VÍTKOVICE RIDERA', 'hokej.cz'),
  ('hcz-714', 'cz-elh', 1999, 'HC Femax Havířov', 'wikipedia'),
  ('hcz-714', 'cz-elh', 2000, 'HC Femax Havířov', 'wikipedia'),
  ('hcz-714', 'cz-elh', 2001, 'HC Havířov Panthers', 'wikipedia'),
  ('hcz-714', 'cz-elh', 2002, 'HC Havířov Panthers', 'wikipedia'),
  ('hcz-8', 'cz-elh', 1993, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 1994, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 1995, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 1996, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 1997, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 1998, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 1999, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2000, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2001, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2002, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2003, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2004, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2005, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2006, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2007, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2008, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2009, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2010, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2011, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2012, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2013, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2014, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2015, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2016, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2017, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2018, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2019, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2020, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2021, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2022, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2023, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2024, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-8', 'cz-elh', 2025, 'HC Sparta Praha', 'hokej.cz'),
  ('hcz-822', 'cz-elh', 2000, 'KLH Chomutov', 'hokej.cz'),
  ('hcz-822', 'cz-elh', 2009, 'KLH Chomutov', 'hokej.cz'),
  ('hcz-822', 'cz-elh', 2011, 'Piráti Chomutov', 'hokej.cz'),
  ('hcz-822', 'cz-elh', 2012, 'Piráti Chomutov', 'hokej.cz'),
  ('hcz-822', 'cz-elh', 2013, 'Piráti Chomutov', 'hokej.cz'),
  ('hcz-822', 'cz-elh', 2014, 'Piráti Chomutov', 'hokej.cz'),
  ('hcz-822', 'cz-elh', 2015, 'Piráti Chomutov', 'hokej.cz'),
  ('hcz-822', 'cz-elh', 2016, 'Piráti Chomutov', 'hokej.cz'),
  ('hcz-822', 'cz-elh', 2017, 'Piráti Chomutov', 'hokej.cz'),
  ('hcz-822', 'cz-elh', 2018, 'Piráti Chomutov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 1993, 'HC Chemopetrol Litvínov', 'wikipedia'),
  ('hcz-823', 'cz-elh', 1994, 'HC Litvínov', 'wikipedia'),
  ('hcz-823', 'cz-elh', 1995, 'HC Litvínov', 'wikipedia'),
  ('hcz-823', 'cz-elh', 1996, 'HC Chemopetrol', 'wikipedia'),
  ('hcz-823', 'cz-elh', 1997, 'HC Chemopetrol', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 1998, 'HC Chemopetrol', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 1999, 'HC Chemopetrol', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2000, 'HC Chemopetrol', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2001, 'HC Chemopetrol', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2002, 'HC Chemopetrol', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2003, 'HC Chemopetrol', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2004, 'HC Chemopetrol', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2005, 'HC Chemopetrol', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2006, 'HC Chemopetrol', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2007, 'HC Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2008, 'HC Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2009, 'HC BENZINA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2010, 'HC BENZINA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2011, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2012, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2013, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2014, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2015, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2016, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2017, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2018, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2019, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2020, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2021, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2022, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2023, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2024, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-823', 'cz-elh', 2025, 'HC VERVA Litvínov', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 1993, 'HC Kladno', 'wikipedia'),
  ('hcz-828', 'cz-elh', 1994, 'HC Poldi Kladno', 'wikipedia'),
  ('hcz-828', 'cz-elh', 1995, 'HC Poldi Kladno', 'wikipedia'),
  ('hcz-828', 'cz-elh', 1996, 'HC Kladno', 'wikipedia'),
  ('hcz-828', 'cz-elh', 1997, 'HC Velvana Kladno', 'wikipedia'),
  ('hcz-828', 'cz-elh', 1998, 'HC Velvana Kladno', 'wikipedia'),
  ('hcz-828', 'cz-elh', 1999, 'HC Velvana Kladno', 'wikipedia'),
  ('hcz-828', 'cz-elh', 2000, 'HC Vagnerplast Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2001, 'HC Vagnerplast Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2002, 'HC Vagnerplast Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2003, 'HC Rabat Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2004, 'HC Rabat Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2005, 'HC Rabat Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2006, 'HC GEUS OKNA Kladno', 'wikipedia'),
  ('hcz-828', 'cz-elh', 2007, 'HC GEUS OKNA Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2008, 'HC GEUS OKNA Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2009, 'HC GEUS OKNA Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2010, 'HC Vagnerplast Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2011, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2012, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2013, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2017, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2018, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2019, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2021, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2022, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2023, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2024, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-828', 'cz-elh', 2025, 'Rytíři Kladno', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2007, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2008, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2009, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2010, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2011, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2012, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2013, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2014, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2015, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2016, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2017, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2018, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2019, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2020, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2021, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2022, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2023, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2024, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-89', 'cz-elh', 2025, 'BK Mladá Boleslav', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 1993, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 1994, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 1995, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 1996, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 1997, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 1998, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 1999, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2000, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2001, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2002, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2003, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2004, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2005, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2006, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2007, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2008, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2009, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2010, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2011, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2012, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2013, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2014, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-9', 'cz-elh', 2015, 'HC Slavia Praha', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 1993, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 1994, 'HC Interconnex Plzeň', 'wikipedia'),
  ('hcz-917', 'cz-elh', 1995, 'HC ZKZ Plzeň', 'wikipedia'),
  ('hcz-917', 'cz-elh', 1996, 'HC ZKZ Plzeň', 'wikipedia'),
  ('hcz-917', 'cz-elh', 1997, 'HC Keramika Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 1998, 'HC Keramika Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 1999, 'HC Keramika Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2000, 'HC Keramika Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2001, 'HC Keramika Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2002, 'HC Keramika Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2003, 'HC Lasselsberger Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2004, 'HC Lasselsberger Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2005, 'HC Lasselsberger Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2006, 'HC Lasselsberger Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2007, 'HC Lasselsberger Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2008, 'HC Lasselsberger Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2009, 'HC Plzeň 1929', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2010, 'HC Plzeň 1929', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2011, 'HC Plzeň 1929', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2012, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2013, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2014, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2015, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2016, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2017, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2018, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2019, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2020, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2021, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2022, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2023, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2024, 'HC Škoda Plzeň', 'hokej.cz'),
  ('hcz-917', 'cz-elh', 2025, 'HC Škoda Plzeň', 'hokej.cz')
on conflict (team_id, league_id, season) do update set name = excluded.name, source = excluded.source;

create or replace function season_team_name(p_team text, p_season int) returns text
language sql stable as $$
  select n.name from team_season_name n where n.team_id = p_team and n.season = p_season
  order by n.league_id = 'cz-elh' desc limit 1
$$;

-- Crests before 2014/15: hokej.cz shows each club's one older crest for every earlier season, so a
-- crest is kept only for seasons in which the club bore the name it had when it last wore that
-- crest (Třinec's "Oceláři" dragon not for 1995-1998, when the club was HC Železárny Třinec).
-- Elsewhere the crest is unknown and a neutral badge is shown rather than an anachronism.
alter table team_season_logo alter column logo_url drop not null;

update team_season_logo l set logo_url = null
from (
  select team_id, league_id, logo_url, max(season) as last_season
  from team_season_logo where logo_url is not null group by 1, 2, 3
) e
where l.team_id = e.team_id and l.league_id = e.league_id and l.logo_url = e.logo_url
  and l.season < 2014
  and season_team_name(l.team_id, l.season) is distinct from season_team_name(e.team_id, e.last_season);

-- A past season without a known crest shows none; only the current season falls back to the
-- club's current crest.
create or replace function season_logo(p_team text, p_season int) returns text
language sql stable as $$
  select case
    when exists (select 1 from team_season_logo l where l.team_id = p_team and l.season = p_season)
      then (select l.logo_url from team_season_logo l where l.team_id = p_team and l.season = p_season
            order by l.league_id = 'cz-elh' desc limit 1)
    when p_season >= (select coalesce(max(season), 0) from game where league_id = 'cz-elh') - 0
      then (select t.logo_url from team t where t.id = p_team)
    else null
  end
$$;
